version: '3.3'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9009:9000"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data

volumes:
  minio-data:
