version: '3.3'

services:
  minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z-cpuv1
    container_name: minio
    # host network
    network_mode: host
    # ports:
    #   - "9009:9000"
    #   - "35971:35971"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data

